/// FIREBASE ACTIONS
export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const SET_SELECTED_ENTITY = 'SET_SELECTED_ENTITY';
export const SET_SELECTED_LEVEL = 'SET_SELECTED_LEVEL';
export const SET_SELECTED_CHART = 'SET_SELECTED_CHART';
